version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 8009:80
    environment:
      - DATABASE_URL=postgresql://root_prod:admin_prod@db:5432/root_prod
    depends_on:
      - db
  
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=root_prod
      - POSTGRES_PASSWORD=admin_prod
      - POSTGRES_DB=root_prod

volumes:
  postgres_data_prod: